### ISSUE TITLE
Description of the base command is duplicated on help

### ISSUE THREAD

**Issue by louisgv** [vadimdemedes/pastel#11]
The description of the whole application is a duplication of the first global command: 
![image](https://user-images.githubusercontent.com/6723574/58381379-4bb9a380-7f71-11e9-96f6-00fc63fd8fe7.png)

I was looking at yargs and all of pastel source in order to do a PR for this, but I couldn't figure what's the best strategy to fix this. My current train of thought was to do a custom option in `boot.js` in this line https://github.com/vadimdemedes/pastel/blob/master/boot.js#L17 

The condition would be if name is index and no subCommand

However, I realized that this will goes inside yargs, so I went to yargs document. After that I couldn't find what is the method to set the description in yargs...

**Comment by vadimdemedes** [comment]
Good catch, I think Pastel could read that description from `description` field in package.json. Will update this soon!

**Comment by louisgv** [comment]
@vadimdemedes yes I was thinking the same thing too, tho I couldn't figure out a way to get that working :sweat_smile:

**Comment by vadimdemedes** [comment]
Fixed in Pastel 2.0 👍
