### ISSUE TITLE
CLI blows up if `commands` folder has non-js files

### ISSUE THREAD

**Issue by hedgerh** [vadimdemedes/pastel#13]
**Expected:**
Pastel will either complain if a file that isn't a valid command `js` file is inside of the `commands` folder, or it will simply ignore that file.

**Actual:**
`yarn dev` and `yarn build` execute with no issue, but when you try to run your CLI, you get the following:

![image](https://user-images.githubusercontent.com/2524280/58744386-d594c100-83f6-11e9-9034-c012a6be41c4.png)

**Steps to reproduce:**
1. Create a pastel project and `commands` folder with an `index.js`.
1. Put a `.jpg` or `.html` or probably any non-JS file in the `commands` folder
1. Run `yarn dev`
1. Attempt to run your CLI.

This may seem like a no-brainer, but it threw me for a loop, and could probably benefit from clearer error handling.

**How it happened:**
I started a pastel project and was intrigued by the `ink-image` component.  I pulled down an image and was having trouble getting it to work properly, so I threw the image into my `commands` folder while trying to figure out how to get it to work.  This caused my CLI to stop working, and the error message wasn't clear, so it took me a minute to realize that it was because it didn't like the `jpg` being in the folder.

I can try to make time to fix this, just let me know what the intended behavior should be.

**Comment by vadimdemedes** [comment]
Thanks for a detailed report, I will take a look at it next week, going on a vacation now. Feel free to submit a PR to fix this though!

**Comment by vadimdemedes** [comment]
Hm actually I wasn't able to reproduce this. Would you be able to share a minimal repo to reproduce this issue?
