### ISSUE TITLE
published pastel@1.0.2 still refers to `pasteljs/boot` in entry.js

### ISSUE THREAD

**Issue by donysukardi** [vadimdemedes/pastel#17]
![image](https://user-images.githubusercontent.com/410792/59549215-d26c0a00-8f8c-11e9-994c-68226296f457.png)

I see that you've already updated the reference in the repo but yet to publish the change. Could you publish 1.0.3 with this commit?

Love parcel and ink! Getting started with them was such a breeze. Thanks!

**Comment by KyleAMathews** [comment]
Just hit the same problem. Also create-pastel-app is still installing pasteljs

**Comment by vadimdemedes** [comment]
Hey guys, sorry for late reply, I'm on vacation. Will fix today!

**Comment by vadimdemedes** [comment]
Published `1.0.3`, thanks for reporting and glad you found Pastel interesting!

**Comment by vadimdemedes** [comment]
Also updated `create-pastel-app`.
