### ISSUE TITLE
"Invariant Violation: Invalid hook call." when command run in project folder with React

### ISSUE THREAD

**Issue by tomhuze** [vadimdemedes/pastel#2]
Thank you for this great project. I ran into this problem: After writing a command, successfully testing in dev, publishing to npm, then uninstalling the dev version and installing the npm version, running the command failed with the React 'Invariant Violation: Invalid hook call.'  This only happens when running the command in a project folder that has React installed. Running command elsewhere works as expected.

**Comment by vadimdemedes** [comment]
Sounds like some React versioning issue. Could you post exact steps/commands I can use that reproduce this issue?

**Comment by adam-lynch** [comment]
Just ran into this 😬. I'll reply if I find a solution

**Comment by adam-lynch** [comment]
I can't reproduce my issue anymore 🤔. I'm not sure what happened but a guess is this: 

1. I somehow I ended up with packages in my `node_modules` in some way that's problematic.
2. My CLI didn't exit when the error happened, so while looking into it, I added a check at the top of my commands to check if React is usable (it calls `useState` in a `try` - `catch`.
3. The call to `useState` was outside any React function, which is another cause for this error.
4. I tried a load of things that didn't work.
5. I moved the `useState` call into the component function and everything is fine now 🤷‍♂

**Comment by vadimdemedes** [comment]
This usually happens when multiple versions of React somehow got installed. I just shipped Pastel 2.0, which is now a lot simpler than Pastel 1.0 and is just another package you import. This should be less magical and have less chances running into this again.
