### ISSUE TITLE
Anyway to get stdin?

### ISSUE THREAD

**Issue by ukabu** [vadimdemedes/pastel#3]
The docs doesn't address reading from stdin. Any suggestion in how to do this with pastel?
Maybe having a hook (`useStdin`) would do it.

**Comment by pacocoursey** [comment]
Pastel is just a framework for Ink apps. I'd recommend reading the [Ink documentation](https://github.com/vadimdemedes/ink). It seems like you want an [ink-text-input](https://github.com/vadimdemedes/ink-text-input) component.

**Comment by ukabu** [comment]
It is really to be able to pipe the output of one command to the ink app. The ink-text-input doesn't serve that purpose.

**Comment by pacocoursey** [comment]
Ah, I misunderstood your use case. Maybe you're looking for `xargs`?

For example, if you want to call a subcommand in git (like `log`) you can do `echo "log" | xargs git`, which uses stdin (the string "log") to format a new git command.

**Comment by vadimdemedes** [comment]
@pacocoursey is right, Pastel only "manages" your CLI commands, essentially. You can get direct access to `stdin` via Ink's `StdinContext`, see https://github.com/vadimdemedes/ink#stdincontext.
