### ISSUE TITLE
how to change build location

### ISSUE THREAD

**Issue by vinodhum** [vadimdemedes/pastel#30]
How to change build location of pastel ?
and how to grab app render object to clear the output ? 
const {clear} = render(<MyApp />);
clear();

**Comment by vinodhum** [comment]
really like pastel for my upcoming project but no support and flexibility.

**Comment by vadimdemedes** [comment]
Pastel 2.0 no longer ships its own dev/build CLI, so you're free to control where files are transpiled to.
