### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by aaronsnig501** [vadimdemedes/pastel#34]
I'm interested in setting up and using pastel for a project that I'm working on, however, I will need to be able to use multiple commands and I don't find that the README is very clear on how to achieve this.

I can see that by creating folders within the `commands` dir it will generate the extra commands, however, whenever I try to do this, it always seems to default to the command inside `commands/index.js`. For example, if I create a folder called `init` inside of `commands` and create a new file called `index.js` and run `my-command init` it still runs the default greeter command in `commands/index.js`.

I tried the `npm run dev` command, but it just says that it's watching the commands directory infinitely, so I don't if I need to open a new terminal and try any new commands. I've even checked the dependency graph to see if I can find any examples of people using multiple commands but I couldn't find any good examples.

Maybe I'm doing something silly, but if I'm not, I'd be happy to work on the documentation to try to make this clearer for other users

**Comment by vadimdemedes** [comment]
I just shipped a brand new version of Pastel and I completely rewrote the docs too. Let me know if something is unclear in the new ones.
