### ISSUE TITLE
Separate pastel into runtime library

### ISSUE THREAD

**Issue by davej** [vadimdemedes/pastel#37]
Currently, pastel needs to be added as a dependency which means that a lot of unnecessary sub-dependencies are bundled to end-users of our CLI.

Could pastel be separated into a runtime dependency that just does what's needed to boot the project and a `devDependency` for doing all the other stuff (Parcel/Babel etc.).

**Comment by adam-lynch** [comment]
Another option (than adding another package): `cli.js` could be compiled/bundled (like the commands are). I.e. the dependencies would be bundled in, rather than requiring `pastel/boot` (which requires the runtime dependencies). Then `pastel` could be in `devDependencies`.

**Comment by vadimdemedes** [comment]
Pastel 2.0 no longer provides its own build/watch/dev CLI and is just a runtime library 👍
