### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by boneskull** [vadimdemedes/pastel#4]
Hi, you requested I open an issue here, so here it is.

1.  The distinction between aliases and short flags is unclear.  How does using a short flag differ from, e.g.:
    ```js
    Foo.aliases = {bar: ['b']}
    ```
    Short option chaining is a thing per POSIX standards (e.g., `foo -abc` is equivalent to `foo -a -b -c`), but unsure if this is supported by yargs-parser?
1. The `///` convention for descriptions is problematic because it must always be hard-coded.  Users cannot dynamically create strings or use template literals.  Probably best to just use a JS string.  :smile: Dynamic descriptions may be unlikely, but unless there's a strong reason, introducing a domain-specific construct like `///` is probably unnecessary.
1. Pastel opens up the idea of reusable commands (but doesn't quite get there, IMO) by distributing them as individual components.  In other words, you could in theory publish a single command to npm (which may (?) work on its own), and compose a new program from third-party commands.  I don't think it's too much of a stretch to get there, but there'd need to be a way to:
    1. Import commands living in `node_modules`
    1. Rename commands (the "default" name could still be the filename, but should allow to be user-defined)
    1. Control which options at the top level are "global" and can be passed to subcommands (see yargs' `global` flag for options)
1. Pastel shouldn't restrict what you can and can't do with yargs.  To that end, it should provide an adapter which "passes through" to yargs.  Another reason is that it will become difficult to maintain unique abstractions for the entire set of yargs' options, especially as yargs adds new features and breaks old ones. Along the same lines, `PropTypes`, while familiar to React users, *may* not be expressive enough to map directly to yargs' types.

I think both Ink and Pastel are cool ideas, and am always excited to see developers driving Node.js-on-the-command-line forward.  Thanks for these projects!

**Comment by boneskull** [comment]
Note that if anyone tries to build e.g., a testing library using this, Pastel will *not* want to be using yargs in the default singleton mode.  Pastel may be able to [disable this](https://github.com/yargs/yargs/blob/master/docs/advanced.md#using-the-non-singleton-interface) right now without negative effects

**Comment by sindresorhus** [comment]
> The distinction between aliases and short flags is unclear. How does using a short flag differ from, e.g.:

The difference is with semantics. A short-flag is a kind of alias, while an alias is not necessarily a short-flag. In the future, we might choose to display short-flags and aliases differently in the output.

**Comment by boneskull** [comment]
seems like you could detect short flags by the nature of their shortness 😁

**Comment by vadimdemedes** [comment]
Thanks for the comprehensive feedback, @boneskull! I'll skip aliases/short flags, Sindre answered that one.

> The /// convention for descriptions is problematic because it must always be hard-coded. Users cannot dynamically create strings or use template literals. Probably best to just use a JS string. 😄 Dynamic descriptions may be unlikely, but unless there's a strong reason, introducing a domain-specific construct like /// is probably unnecessary.

As for dynamically creating strings, it's not going to be possible for now, because Pastel doesn't extract comments at runtime, Pastel parses component file with Babel. So if you'd have variables in your description template string or would build it dynamically, Pastel wouldn't recognize it.

> Pastel opens up the idea of reusable commands (but doesn't quite get there, IMO) by distributing them as individual components. In other words, you could in theory publish a single command to npm (which may (?) work on its own), and compose a new program from third-party commands.

Interesting idea, but I'm having a hard time coming up with actual commands that could be universally reused across various CLIs. Do you have any ideas for these?

> Control which options at the top level are "global" and can be passed to subcommands (see yargs' global flag for options)

Yep, I was thinking we could allow developers to have either `pastel.config.js` or some root component, which wraps command components, where you could define global options. Will think more about this!

> Pastel shouldn't restrict what you can and can't do with yargs. To that end, it should provide an adapter which "passes through" to yargs. Another reason is that it will become difficult to maintain unique abstractions for the entire set of yargs' options, especially as yargs adds new features and breaks old ones. Along the same lines, PropTypes, while familiar to React users, may not be expressive enough to map directly to yargs' types.

That's actually why I like Pastel's idea, I don't have to think about `yargs` and remember its API. What kind of things you would want to have access to in `yargs`, that Pastel doesn't currently have?

**Comment by sindresorhus** [comment]
> seems like you could detect short flags by the nature of their shortness 😁

What if you want an alias for a short-flag? Meaning, you renamed a short-flag, but want to support both versions. Having this separation is important so the system can differentiate. For example, the help documentation could be different for short-flags and actual aliases.
