### ISSUE TITLE
Question:  is pastel 1.1.1 compatible with react-ink 3?

### ISSUE THREAD

**Issue by elricb** [vadimdemedes/pastel#41]
The latest pastel version (pastel@1.1.1 at time of writing) has a react-ink "peerDependencies" of "ink@^2.1.1" listed.  Is it okay to use ink@^3.0.0 with pastel@1.1.1?

**Comment by adam-lynch** [comment]
We're using it awhile now

**Comment by alechp** [comment]
Looks like I'm having the same issue. 

## Steps
1. `npm init`
2. `npm install pastel ink react prop-types --save`

## Error output
![Screen Shot 2020-11-08 at 2 56 09 PM](https://user-images.githubusercontent.com/3058939/98486525-93b69f80-21d2-11eb-96c7-5a468aec9cfe.png)

<details><summary>Error output (text)</summary>
<p>
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: pastel-ink@1.0.0
npm ERR! Found: ink@3.0.8
npm ERR! node_modules/ink
npm ERR!   ink@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer ink@"^2.1.1" from pastel@1.1.1
npm ERR! node_modules/pastel
npm ERR!   pastel@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/alechp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alechp/.npm/_logs/2020-11-08T22_55_33_561Z-debug.log
</p></details>

**Comment by vadimdemedes** [comment]
Just shipped Pastel 2.0, which supports the latest Ink 4.0 👍
