### ISSUE TITLE
question: I want to learn use pastel with ink-table,can you give me some demo code...

### ISSUE THREAD

**Issue by Developer27149** [vadimdemedes/pastel#42]
and thanks.I can not understand it.ink-table use render function,but pastel not.
I try to export it,but a lot of error.

```js
// data is valid array from demo code
const Basic = () => <Table data={data} />;
export default Basic;
```
but error:
```js

  ERROR Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely  
       forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

       Check the render method of `Skeleton`.
```

**Comment by AeonFr** [comment]
I was successfully able to use ink-table alongside pastel. Looks like your error comes from the `Skeleton` component. Can you provide a more complete stack trace?

**Comment by diego-carvallo** [comment]
Hi I created a new project using `npx create-pastel-app` and I followed the sample [here](https://github.com/maticzav/ink-table?tab=readme-ov-file#usage) to use ink-table, so I have:

```
import Table from 'ink-table';

const data = [
  {
    name: 'Sosa Saunders',
    gender: 'male',
    age: 17,
  },
  {
    name: 'Angelina Kirk',
    gender: 'female',
    age: 33,
  }
]

export const alias = 'n';

export default function normalize() {
	return <Table data={data} />;
}
```

 but I get this error when running npm build:

<img width="955" alt="image" src="https://github.com/user-attachments/assets/b2b296c8-b0ba-4ce0-bac6-11da7f3fab89">


Please help!
cc @AeonFr
