### ISSUE TITLE
Include static files?

### ISSUE THREAD

**Issue by qjack001** [vadimdemedes/pastel#47]
Is there a way to include static files in the generated `build/` folder? I have a Go binary that I want to include in the distribution, which is run by the Pastel commands. I can sort of hack it to work by automating moving the file into the folder: `"build": "pastel build && cp -f gocode build"` — but this seems like not the best solution. When running `pastel dev`, this file is constantly overridden.

**Comment by vadimdemedes** [comment]
Pastel 2.0 no longer provides its own build tools, so you're free to ship any files you'd like.
