### ISSUE TITLE
Запит функції? / Feature Request?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [vadimdemedes/pastel#57]
українська / Ukrainian

Чи може/чи буде "пастель" у своєму поточному стані підтримувати NodeGUI?

 https://github.com/nodegui/nodegui

 Якщо ні, які кроки будуть потрібні для досягнення цього?

англійська / English

Could/Would "pastel" in its current state support NodeGUI?

https://github.com/nodegui/nodegui

If it doesn't, what steps would be needed in order to achieve this?

**Comment by vadimdemedes** [comment]
There's no connection between these projects. Pastel is for building CLI apps, NodeGui is for desktop apps.
