### ISSUE TITLE
vscode debugging

### ISSUE THREAD

**Issue by endquote** [vadimdemedes/pastel#58]
Is there a `.vscode/launch.json` configuration that would work to allow debugging through a typescript pastel project?

**Comment by vadimdemedes** [comment]
Pastel is a regular dependency, so if you set up a debugger for a TypeScript project, it should work. I don't use it myself, so can't help setting one up.

**Comment by endquote** [comment]
Thanks for the helpful reply.

In case anyone else is wondering:

Just add `"sourceMap": true` under `compilerOptions` in `tsconfig.json`.

Add this `.vscode/launch.json` file:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/source/cli.tsx",
      "preLaunchTask": "tsc: build - tsconfig.json",
      "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
      ]
    }
  ]
}
```

**Comment by vadimdemedes** [comment]
Thanks for posting your setup, hope it'll be useful for anyone looking 👍
