### ISSUE TITLE
Nested directories cause build to fail if `index.js` is not included

### ISSUE THREAD

**Issue by ryanhair** [vadimdemedes/pastel#6]
Currently, given the directory structure:

```
demo
  commands
    nested
      hello.js
```
(note the missing `commands/nested/index.js`)

Without a nested `index.js`, the build fails. Note that not having an `index.js` file directly under `/commands` does _not_ cause the build to fail; instead it currently doesn’t display anything. See [related issue](https://github.com/vadimdemedes/pastel/issues/5)

**Comment by vadimdemedes** [comment]
This turned out to be a harder fix, working on it!

**Comment by shyamks** [comment]
Looks like the **buildPath** in `commands.json` is being built wrong.
