### ISSUE TITLE
Link to form example?

### ISSUE THREAD

**Issue by erikras** [vadimdemedes/pastel#9]
I wonder if there could/should be a section in the readme linking to example projects like this one I made?

https://github.com/final-form/rff-cli-example

**Comment by vadimdemedes** [comment]
I think that kind of example would belong to [Ink](https://github.com/vadimdemedes/ink) repository instead :)

**Comment by erikras** [comment]
Good idea. https://github.com/vadimdemedes/ink/pull/196
